version: "3.8"

services:
# TIER 1: FRONTEND (NGINX)
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    container_name: simple_notes_frontend
    ports:
      - "8080:80"
    restart: unless-stopped
    depends_on:
      - backend
 
# TIER 2: BACKEND (FLASK)
  backend:
    build:
      context: ./backend    # adjust if Dockerfile elsewhere
      dockerfile: dockerfile
    container_name: simple_notes_backend
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    restart: unless-stopped

# TIER 3: DATABASE (REDIS)
  redis:
    image: "redis:alpine"
    container_name: simple_notes_redis
    volumes:
      - redis-data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 2s
      retries: 5


volumes:
  redis-data:
 